# https://kubernetes.github.io/ingress-nginx/deploy/#quick-start
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: beta
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /prisma/docs
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   rewrite ^/stylesheets/(.*)$ /app/stylesheets/$1 redirect;
    #   rewrite ^/images/(.*)$ /app/images/$1 redirect;
spec:
  rules:
    - host: api.localdev.me
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /prisma(/|$)(.*)
            backend:
              service:
                name: nestjs-api-svc
                port:
                  number: 4000
          # - pathType: Prefix
          #   path: '/'
          #   backend:
          #     service:
          #       name: nestjs-api-svc
          #       port:
          #         number: 4000
